apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: Resource Inventory
    oda.tmforum.org/funtionalBlockName: Production
  name: TAG_REALESE_NAME - Resource Inventory
spec:
  componentKinds:
  - group: core
    kind: Inventory
  coreFunction:
    exposedAPIs: 
      - name: ResourceInventoryManagement
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF639_ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
        required: true
        implementation: /{{.Release.Name}}-ResourceInventoryManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/resourceInventoryManagement/v4/
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/resourceInventoryManagement/v4/docs
        port: 8080
      - name: ProcessFlowManagement
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ProcessFlowManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/processFlowManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/processFlowManagement/v4/docs
        port: 8080
      - name: Event
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-Event
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/event/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/event/v4/docs
        port: 8080
    
    dependantAPIs: 
      - name: ResourceCatalogManagement
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF634_ResourceCatalog/master/TMF634-ResourceCatalog-v4.0.0.swagger.json
        required: true
        implementation: /{{.Release.Name}}-ResourceCatalogManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/resourceCatalog/v4/
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/resourceCatalog/v4/docs
        port: 8080
        
      - name: ResourceInventoryManagement
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF639_ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-ResourceInventory
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/resourceInventory/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/resourceInventory/v4/docs
        port: 8080
     
      - name: PartyRoleManagement
        specification: https://https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-PartyRoleManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4/docs
        port: 8080
        
      - name: GeographicAddressManagement
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.1.swagger.json
        implementation: /{{.Release.Name}}-GeographicAddressManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/geographicAddressManagement/v4/
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/geographicAddressManagement/v4/docs
        port: 8080
        
      - name: GeographicSiteManagement
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF674_GeographicSite/master/TMF674-GeographicSite-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-GeographicSiteManagement
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/geographicSiteManagement/v4/
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/geographicSiteManagement/v4/docs
        port: 8080
        
      - name: GeographicLocationfication
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF675_GeographicLocation/master/TMF675-GeographicLocation-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-GeographicLocation
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/geographicLocation/v4/
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/geographicLocation/v4/docs
        port: 8080
        
      - name: UserRolesPermissions
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesPermissions/master/TMF672-UserRolePermission-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-UserRolesPermissions
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolesPermissions/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolesPermissions/v4/docs
        port: 8080
        
      - name: Event
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-Event
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/event/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/event/v4/docs
        port: 8080

    managementAPIs: []
  eventNotification:
    PublishedEvent: []
    SubscribedEvent: []
  maintainers:
    - email: kamal.maghsoudlou@ericsson.com
      name: Kamal Maghsoudlou
  management: []
  owners:
    - email: kamal.maghsoudlou@ericsson.com
      name: Kamal Maghsoudlou
  security:
    securitySchemes: 
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  selector:
    matchLabels:
      oda.tmforum.org/componentName: Resource Inventory
  type: Resource Inventory
  version: 1.0.0

