apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: Resource Inventory
    oda.tmforum.org/funtionalBlockName: Production
  name: TAG_REALESE_NAME - Resource Inventory
spec:
  componentKinds:
  - group: core
    kind: Inventory
  coreFunction:
    exposedAPIs: 
      ResourceInventoryManagement:
          version: 4.0
          id: TMF639
          resource:
                - GET
                - GET /id
                - POST
                - PATCH
                - DELETE
      ResourcePoolManagement:
          version: 4.0
          id: TMF685
          resourcePool:
                - POST
                - PATCH
                - DELETE
          reservation:
                - GET
                - GET /id
                - POST
                - PATCH
          availabilityCheck:
                - GET
                - GET /id
                - POST
          push:
                - GET
                - GET /id
                - POST
          extract:
                - GET
                - GET /id
                - POST
      ProcessFlowManagement:
          version: 4.0
          id: TMF701
          processFlow:
              - POST
              - GET
              - GET /id
              - DELETE
          taskFlow:
              - PATCH
              - GET
              - GET /id
              
      Event:
          version: 4.0
          id: TMF688
          listener:
                - POST
          hub:
                - POST
                - DELETE

    dependantAPIs: 
      ResourceCatalogManagement:
          version: 4.0
          id: TMF634
          resourceSpecification:
              - GET
              - GET /id
      PartyRoleManagement:
          version: 4.0
          id : TMF669
          partyRole:
              - GET
              - GET /id
      Party:
          version: 4.0
          id : TMF632
          individual:
              - GET
              - GET /id
          organization:
              - GET
              - GET /id  
      UserRolePermission:
          version: 4.0
          id : TMF672
          permission:
              - GET
              - GET /id
      GeographicAddressManagement:
          version: 4.0
          id : TMF673
          geographicAddress:
              - GET
              - GET /id
          geographicSubAddress:
              - GET
              - GET /id  
      GeographicSiteManagement:
          version: 4.0
          id : TMF674
          geographicSite:
              - GET
              - GET /id
      GeographicLocation:
          version: 4.0
          id : TMF675
          geographicLocation:
              - GET
              - GET /id
      ResourceInventoryManagement:
          version: 4.0
          id: TMF639
          resource:
                - GET
                - GET /id
                - POST
                - PATCH
                - DELETE
      Event:
          version: 4.0
          id : TMF688
          event:
              - POST
              - GET /id
              - GET
    managementAPIs: []
  eventNotification:
    PublishedEvent:
       ResourceInventoryManagement:
        - resourceCreateEvent
        - resourceAttributeValueChangeEvent
        - resourceStateChangeEvent
        - resourceDeleteEvent
       ResourcePoolManagement:
        - reservationStateChangeNotification
        - informationRequiredNotification
        - resourceReservationCreationNotification
        - resourceReservationRemoveNotification
       ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent
    SubscribedEvent:
       ResourceCatalogManagement:
        - resourceSpecificationDeleteEvent
       ResourceInventoryManagement:
        - resourceCreateEvent
        - resourceAttributeValueChangeEvent
        - resourceStateChangeEvent
        - resourceDeleteEvent
       PartyRoleManagement:
        - partyRoleDeleteEvent
       UserRolePermission:
        - permissionDeleteEvent
       GeographicSiteManagement:
        - geographicSiteDeleteEvent
       GeographicLocation:
        - geographicLocationDeleteEvent
       Party:
        - individualDeleteEvent
        - organizationDeleteEvent
  maintainers:
    - email: kamal.maghsoudlou@ericsson.com
      name: Kamal Maghsoudlou
  management: []
  owners:
    - email: kamal.maghsoudlou@ericsson.com
      name: Kamal Maghsoudlou
  security:
    securitySchemes: 
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  selector:
    matchLabels:
      oda.tmforum.org/componentName: Resource Inventory
  type: Resource Inventory
  version: 1.0.0
