apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
    labels:
    -   name: TAG_REALESE_NAME - Resource Inventory
    oda.tmforum.org/componentName: Resource Inventory
    oda.tmforum.org/funtionalBlockName: Production
spec:
    componentKinds:
    -   group: core
        kind: Inventory
    coreFunction:
        exposedAPIs:
        -   name: ResourceInventoryManagement
            specification: ''
            required: true
            implementation: /{.Release.Name}-ResourceInventoryManagement
            path: /{.Release.Name}/tmf-api/ResourceInventoryManagement/v4
            developerUI: /{.Release.Name}/tmf-api/ResourceInventoryManagement/v4/docs
            port: 8080
        -   name: ResourcePoolManagement
            specification: ''
            required: true
            implementation: /{.Release.Name}-ResourcePoolManagement
            path: /{.Release.Name}/tmf-api/ResourcePoolManagement/v4
            developerUI: /{.Release.Name}/tmf-api/ResourcePoolManagement/v4/docs
            port: 8080
        -   name: ProcessFlowManagement
            specification: ''
            required: true
            implementation: /{.Release.Name}-ProcessFlowManagement
            path: /{.Release.Name}/tmf-api/ProcessFlowManagement/v4
            developerUI: /{.Release.Name}/tmf-api/ProcessFlowManagement/v4/docs
            port: 8080
        -   name: Event
            specification: ''
            required: true
            implementation: /{.Release.Name}-Event
            path: /{.Release.Name}/tmf-api/Event/v4
            developerUI: /{.Release.Name}/tmf-api/Event/v4/docs
            port: 8080
        dependantAPIs:
        -   name: ResourceCatalogManagement
            specification: ''
            required: true
            implementation: /{.Release.Name}-ResourceCatalogManagement
            path: /{.Release.Name}/tmf-api/ResourceCatalogManagement/v4
            developerUI: /{.Release.Name}/tmf-api/ResourceCatalogManagement/v4/docs
            port: 8080
        -   name: PartyRoleManagement
            specification: ''
            required: true
            implementation: /{.Release.Name}-PartyRoleManagement
            path: /{.Release.Name}/tmf-api/PartyRoleManagement/v4
            developerUI: /{.Release.Name}/tmf-api/PartyRoleManagement/v4/docs
            port: 8080
        -   name: Party
            specification: ''
            required: true
            implementation: /{.Release.Name}-Party
            path: /{.Release.Name}/tmf-api/Party/v4
            developerUI: /{.Release.Name}/tmf-api/Party/v4/docs
            port: 8080
        -   name: UserRolePermission
            specification: ''
            required: true
            implementation: /{.Release.Name}-UserRolePermission
            path: /{.Release.Name}/tmf-api/UserRolePermission/v4
            developerUI: /{.Release.Name}/tmf-api/UserRolePermission/v4/docs
            port: 8080
        -   name: GeographicAddressManagement
            specification: ''
            required: true
            implementation: /{.Release.Name}-GeographicAddressManagement
            path: /{.Release.Name}/tmf-api/GeographicAddressManagement/v4
            developerUI: /{.Release.Name}/tmf-api/GeographicAddressManagement/v4/docs
            port: 8080
        -   name: GeographicSiteManagement
            specification: ''
            required: true
            implementation: /{.Release.Name}-GeographicSiteManagement
            path: /{.Release.Name}/tmf-api/GeographicSiteManagement/v4
            developerUI: /{.Release.Name}/tmf-api/GeographicSiteManagement/v4/docs
            port: 8080
        -   name: GeographicLocation
            specification: ''
            required: true
            implementation: /{.Release.Name}-GeographicLocation
            path: /{.Release.Name}/tmf-api/GeographicLocation/v4
            developerUI: /{.Release.Name}/tmf-api/GeographicLocation/v4/docs
            port: 8080
        -   name: ResourceInventoryManagement
            specification: ''
            required: true
            implementation: /{.Release.Name}-ResourceInventoryManagement
            path: /{.Release.Name}/tmf-api/ResourceInventoryManagement/v4
            developerUI: /{.Release.Name}/tmf-api/ResourceInventoryManagement/v4/docs
            port: 8080
        -   name: Event
            specification: ''
            required: true
            implementation: /{.Release.Name}-Event
            path: /{.Release.Name}/tmf-api/Event/v4
            developerUI: /{.Release.Name}/tmf-api/Event/v4/docs
            port: 8080
        managementAPIs: []
    eventNotifications:
        eventNotification: []
        subscribedEvents: []
    maintainers:
    -   email: kamal.maghsoudlou@ericsson.com
        name: Kamal Maghsoudlou
    management: []
    owners:
    -   email: kamal.maghsoudlou@ericsson.com
        name: Kamal Maghsoudlou
    security:
        securitySchemes:
            bearerAuth:
                type: http
                scheme: bearer
                bearerFormat: JWT
    selector:
        matchLabels:
            oda.tmforum.org/componentName: Resource Inventory
    type: Resource Inventory
    version: 1.0.0
